import test from "node:test";
import assert from "node:assert/strict";

import {
  architectureDiagramSchema,
  chatTurnRequestSchema,
  pageMetadataSchema,
  systemStatusSchema,
} from "../shared/schema.ts";

test("chatTurnRequestSchema normalizes snake_case fields", () => {
  const parsed = chatTurnRequestSchema.parse({
    content: "  rebuild the wiki  ",
    session_id: "sess-123",
    confirmation_id: "confirm-123",
  });

  assert.equal(parsed.content, "rebuild the wiki");
  assert.equal(parsed.sessionId, "sess-123");
  assert.equal(parsed.confirmationId, "confirm-123");
});

test("pageMetadataSchema applies defaults", () => {
  const parsed = pageMetadataSchema.parse({});

  assert.deepEqual(parsed.tags, []);
  assert.equal(parsed.autoGenerated, false);
  assert.deepEqual(parsed.diagramIds, []);
  assert.deepEqual(parsed.custom, {});
});

test("architectureDiagramSchema accepts the recovered diagram contract", () => {
  const parsed = architectureDiagramSchema.parse({
    id: "main-architecture",
    name: "Kijko Ecosystem Architecture",
    nodes: [
      { id: "wikiagent", label: "WikiAgent", type: "service", url: "/chat" },
      { id: "repo-1", label: "panopticon", type: "repo", url: "/wiki/panopticon" },
    ],
    edges: [{ from: "wikiagent", to: "repo-1", label: "monitors" }],
    lastGenerated: new Date().toISOString(),
    linkedRepos: ["panopticon"],
  });

  assert.equal(parsed.format, "json");
  assert.equal(parsed.nodes.length, 2);
});

test("systemStatusSchema validates the recovered status payload", () => {
  const parsed = systemStatusSchema.parse({
    status: "healthy",
    version: "1.0.0-recovered",
    uptimeSeconds: 10,
    components: { api: "running" },
    monitoredRepos: 2,
    totalPages: 5,
    lastBuild: null,
    nextPoll: null,
    agentState: "idle",
    pendingConfirmations: 0,
    notebookReachable: true,
  });

  assert.equal(parsed.status, "healthy");
  assert.equal(parsed.agentState, "idle");
});
