import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const audienceEnum = z.enum(["internal", "external", "both"]);
export type Audience = z.infer<typeof audienceEnum>;

export const repoStatusEnum = z.enum(["active", "paused", "error", "archived"]);
export const buildStatusEnum = z.enum(["queued", "building", "completed", "failed"]);
export const messageRoleEnum = z.enum(["user", "assistant", "system", "agent"]);
export const agentStateEnum = z.enum(["idle", "processing", "building", "deploying", "error"]);
export const diagramFormatEnum = z.enum(["d2", "mermaid", "json"]);

export const pageMetadataSchema = z.object({
  repoUrl: z.string().url().optional().nullable(),
  tags: z.array(z.string()).default([]),
  component: z.string().optional().nullable(),
  autoGenerated: z.boolean().default(false),
  sourceNotebook: z.string().optional().nullable(),
  diagramIds: z.array(z.string()).default([]),
  custom: z.record(z.string()).default({}),
});
export type PageMetadata = z.infer<typeof pageMetadataSchema>;

export const pendingConfirmationSchema = z.object({
  id: z.string(),
  summary: z.string(),
  target: z.string().nullable().optional(),
  actionType: z.string(),
});
export type PendingConfirmation = z.infer<typeof pendingConfirmationSchema>;

export const diagramNodeSchema = z.object({
  id: z.string(),
  label: z.string(),
  type: z.enum(["gateway", "service", "module", "repo", "infrastructure", "tool", "group"]),
  url: z.string(),
});
export const diagramEdgeSchema = z.object({
  from: z.string(),
  to: z.string(),
  label: z.string().default(""),
});
export const architectureDiagramSchema = z.object({
  id: z.string(),
  name: z.string(),
  format: diagramFormatEnum.default("json"),
  nodes: z.array(diagramNodeSchema),
  edges: z.array(diagramEdgeSchema),
  lastGenerated: z.string(),
  linkedRepos: z.array(z.string()).default([]),
});
export type ArchitectureDiagram = z.infer<typeof architectureDiagramSchema>;

export const chatSessionSchema = z.object({
  id: z.string(),
  state: agentStateEnum.default("idle"),
  createdAt: z.string(),
  updatedAt: z.string(),
});
export type ChatSession = z.infer<typeof chatSessionSchema>;

export const agentActionSchema = z.object({
  id: z.string().optional(),
  type: z.string(),
  target: z.string().optional().nullable(),
  status: z.string(),
  summary: z.string().optional().nullable(),
});
export type AgentAction = z.infer<typeof agentActionSchema>;

export const systemStatusSchema = z.object({
  status: z.string(),
  version: z.string(),
  uptimeSeconds: z.number(),
  components: z.record(z.string()),
  monitoredRepos: z.number(),
  totalPages: z.number(),
  lastBuild: z.string().nullable(),
  nextPoll: z.string().nullable(),
  agentState: agentStateEnum,
  pendingConfirmations: z.number(),
  notebookReachable: z.boolean(),
});
export type SystemStatus = z.infer<typeof systemStatusSchema>;

export const chatTurnRequestSchema = z
  .object({
    type: z.string().optional(),
    content: z.string().min(1).max(4000),
    sessionId: z.string().optional(),
    session_id: z.string().optional(),
    confirmationId: z.string().optional(),
    confirmation_id: z.string().optional(),
  })
  .transform((value) => ({
    content: value.content.trim(),
    sessionId: value.sessionId ?? value.session_id,
    confirmationId: value.confirmationId ?? value.confirmation_id,
  }));
export type ChatTurnRequest = z.infer<typeof chatTurnRequestSchema>;

export const wikiPages = sqliteTable("wiki_pages", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  slug: text("slug").notNull().unique(),
  title: text("title").notNull(),
  audience: text("audience").notNull().default("internal"),
  author: text("author").notNull().default("agent"),
  wordCount: integer("word_count").notNull().default(0),
  content: text("content").notNull().default(""),
  metadata: text("metadata").notNull().default("{}"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const insertWikiPageSchema = createInsertSchema(wikiPages).omit({ id: true });
export type InsertWikiPage = z.infer<typeof insertWikiPageSchema>;
export type WikiPage = typeof wikiPages.$inferSelect;

export const repos = sqliteTable("repos", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  url: text("url").notNull().unique(),
  name: text("name").notNull(),
  branch: text("branch").notNull().default("main"),
  lastChecked: text("last_checked"),
  lastCommitSha: text("last_commit_sha"),
  status: text("status").notNull().default("active"),
  pollIntervalMinutes: integer("poll_interval_minutes").notNull().default(10),
  visibility: text("visibility").notNull().default("private"),
});

export const insertRepoSchema = createInsertSchema(repos).omit({ id: true });
export type InsertRepo = z.infer<typeof insertRepoSchema>;
export type Repo = typeof repos.$inferSelect;

export const chatMessages = sqliteTable("chat_messages", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  sessionId: text("session_id").notNull(),
  role: text("role").notNull(),
  content: text("content").notNull(),
  action: text("action"),
  timestamp: text("timestamp").notNull(),
});

export const insertChatMessageSchema = createInsertSchema(chatMessages).omit({ id: true });
export type InsertChatMessage = z.infer<typeof insertChatMessageSchema>;
export type ChatMessage = typeof chatMessages.$inferSelect;

export const buildEvents = sqliteTable("build_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  buildId: text("build_id").notNull().unique(),
  audience: text("audience").notNull(),
  status: text("status").notNull().default("queued"),
  reason: text("reason"),
  startedAt: text("started_at"),
  completedAt: text("completed_at"),
  createdAt: text("created_at").notNull(),
});

export const insertBuildEventSchema = createInsertSchema(buildEvents).omit({ id: true });
export type InsertBuildEvent = z.infer<typeof insertBuildEventSchema>;
export type BuildEvent = typeof buildEvents.$inferSelect;

export const notebookSources = sqliteTable("notebook_sources", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  notebookId: text("notebook_id").notNull(),
  sourceId: text("source_id").notNull().unique(),
  title: text("title").notNull(),
  type: text("type").notNull(),
  summary: text("summary"),
  lastSynced: text("last_synced"),
});

export const insertNotebookSourceSchema = createInsertSchema(notebookSources).omit({ id: true });
export type InsertNotebookSource = z.infer<typeof insertNotebookSourceSchema>;
export type NotebookSource = typeof notebookSources.$inferSelect;
